#!/usr/bin/env python
# mrcepid-runnassociationtesting 0.0.1
# Generated by dx-app-wizard.
#
# Author: Eugene Gardner (eugene.gardner at mrc.epid.cam.ac.uk)
#
# DNAnexus Python Bindings (dxpy) documentation:
#   http://autodoc.dnanexus.com/bindings/python/current/
import tarfile
import sys

# Update system search paths to look for modules appropriately
# We have to do this to get modules to run properly on DNANexus while still enabling easy editing in PyCharm
sys.path.append('/')
sys.path.append('/runassociationtesting/')

from runassociationtesting.module_loader import *


@dxpy.entry_point('main')
def main(mode: str, output_prefix: str, input_args: str):

    # Define the package to search for based on the 'mode' requested
    module_loader = conditional_import(f'{mode}.loader')

    # All packages MUST have a 'start_module' class by definition
    loaded_module = module_loader(output_prefix, input_args)
    loaded_module.start_module()

    # Create tar of all possible output files
    output_tarball = output_prefix + ".assoc_results.tar.gz"

    tar = tarfile.open(output_tarball, "w:gz")
    for file in loaded_module.get_outputs():
        tar.add(file)
    tar.close()

    # Have to do 'upload_local_file' to make sure the new file is registered with dna nexus
    output = {"output_tarball": dxpy.dxlink(dxpy.upload_local_file(output_tarball))}

    return output


dxpy.run()
